services:
  - type: web
    name: nikola-frontend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: VITE_BACKEND_URL
        value: https://nikola-backend.onrender.com
